messages:
  no-permission: "&cYou don't have permission to use this command!"
  player-only: "&cThis command can only be used by players!"
  player-not-found: "&cPlayer not found!"
  gamemode-changed: "&aGamemode changed to %gamemode%!"
  gamemode-changed-other: "&aChanged %player%'s gamemode to %gamemode%!"
  god-enabled: "&aGod mode enabled!"
  god-disabled: "&cGod mode disabled!"
  god-enabled-other: "&aGod mode enabled for %player%!"
  god-disabled-other: "&cGod mode disabled for %player%!"
  inventory-opened: "&aOpened %player%'s inventory!"
  inventory-opened-target: "&a%player% opened your inventory!"
  enderchest-opened: "&aOpened enderchest!"
  enderchest-opened-other: "&aOpened %player%'s enderchest!"
  enderchest-opened-target: "&a%player% opened your enderchest!"
  item-fixed: "&aItem has been fixed!"
  no-item: "&cYou must hold an item to fix it!"
  tpa-sent: "&aTeleport request sent to %player%!"
  tpa-received: "&a%player% wants to teleport to you! Type /tpaaccept to accept or /tpadeny to deny."
  tpa-self: "&cYou cannot send a teleport request to yourself!"
  tpa-already-pending: "&cThis player already has a pending teleport request!"
  tpa-no-request: "&cYou don't have any pending teleport requests!"
  tpa-player-offline: "&cThe player who sent the request is offline!"
  tpa-accepted: "&a%player% accepted your teleport request!"
  tpa-accepted-target: "&aYou accepted %player%'s teleport request!"
  tpa-denied: "&c%player% denied your teleport request!"
  tpa-denied-target: "&cYou denied %player%'s teleport request!"
  tpa-denied-offline: "&cRequest denied. The player is offline."
  tpa-expired-sender: "&cYour teleport request to %player% has expired!"
  tpa-expired-target: "&cThe teleport request from %player% has expired!"
  trash-opened: "&aOpened trash menu!" 