name: NexusPlugin
version: '${version}'
main: com.nexus.nexusplugin.NexusPlugin
api-version: '1.21'
commands:
  gamemode:
    description: Set gamemode for yourself or another player
    usage: /gamemode <type> [player]
  god:
    description: Toggle god mode for yourself or another player
    usage: /god [player]
  openinv:
    description: Open another player's inventory
    usage: /openinv <player>
  enderchest:
    description: Open your or another player's enderchest
    usage: /enderchest [player]
  fix:
    description: Fix the durability of the item in your hand
    usage: /fix
  tpa:
    description: Send a teleport request to a player
    usage: /tpa <player>
  tpaaccept:
    description: Accept a pending teleport request
    usage: /tpaaccept
  tpadeny:
    description: Deny a pending teleport request
    usage: /tpadeny
  trash:
    description: Open trash menu to dispose items
    usage: /trash

permissions:
  nexusplugin.gamemode:
    default: op
  nexusplugin.god:
    default: op
  nexusplugin.openinv:
    default: op
  nexusplugin.openinv.edit:
    default: op
  nexusplugin.enderchest:
    default: op
  nexusplugin.enderchest.others:
    default: op
  nexusplugin.enderchest.edit:
    default: op
  nexusplugin.fix:
    default: op
  nexusplugin.tpa:
    default: true
  nexusplugin.trash:
    default: true 